### ISSUE TITLE
您好，关于采访音频，只有主持人的声音没有被采访人的声音

### ISSUE THREAD

**Issue by r1ght0us** [ARP-issues/ARP-issues.github.io#1]

**Comment by DSOTM-pf** [comment]
Hello, thanks for your reply.

I double-check the interview audio records and P2, P5, P6 only have host voices. It's because the external microphone was used during the interview, but only the sound of the built-in microphone was recorded.

During the interview, the interviewee's answers were also recorded in text, which covered most of the information. You can download it in the below zip.

Thank you.
[InterviewData.zip](https://github.com/ARP-issues/ARP-issues.github.io/files/8333258/InterviewData.zip)

**Comment by r1ght0us** [comment]
@wowhhh Thank you for your reply. Your research is of great help to my paper~
